apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
    - git:
        repoURL: https://github.com/crizstian/guestbook-delivery.git
        revision: HEAD
        files:
          - path: "cluster-config/**/config.json"
  template:
    metadata:
      name: "{{cluster_name}}-guestbook"
      labels:
        harness.io/envRef: "{{environment}}"
        harness.io/serviceRef: "{{harness_service}}"
        harness.io/buildRef: "{{image_tag}}"
    spec:
      project: 4b26d004
      source:
        repoURL: https://github.com/crizstian/guestbook-delivery.git
        targetRevision: HEAD
        path: "base"
        kustomize:
          namePrefix: "{{environment}}-"
          images:
            - crizstian/guestbook:{{image_tag}}
      destination:
        server: "{{server_address}}"
        namespace: "guestbook-{{environment}}"
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - PruneLast=true
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
